### ISSUE TITLE
Modify template of the Y

### ISSUE THREAD

**Issue by KyusangCho** [teresaleelim/intprojectmanagement#56]
As/is 
difficult to create plan ID 

To/be
create plan ID by the File# and Yarn code automatically
Plan ID = Year + Seq# (24 + 0001~9999)
![image](https://github.com/teresaleelim/intprojectmanagement/assets/2341212/7424f8c7-bddb-4a70-9a25-a26de7f3ec76)

**Comment by SofiaAMorales** [comment]
- [x] Transferred page
- [x] Used page
- [x] Change Manual
- [x] Change correlative for PO and Transfer
